site_name: Mutagen Documentation
site_url: https://mutagen-modding.github.io/Mutagen/

repo_name: Mutagen-Modding/Mutagen
repo_url: https://github.com/Mutagen-Modding/Mutagen

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Mutagen-Modding

markdown_extensions:
  - admonition
  - tables
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences 
  - pymdownx.tasklist
  - def_list
  - meta
  - md_in_html
  - attr_list
  - footnotes
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_css:
  - Custom/Stylesheets/extra.css

plugins:
  - search

theme:
  name: material
  palette:
    primary: deep purple
    accent: deep orange
    scheme: slate
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.indexes 
    
nav:
  - Home: index.md
  - Big Cheat Sheet: Big-Cheat-Sheet.md
  - Plugin Record Suite: Plugin-Record-Suite.md
    - Generated Classes: Generated-Classes.md
    - Binary Importing: Binary-Importing.md
    - Binary Overlay: Binary-Overlay.md
    - Interfaces (Aspect/Link/Getters): Interfaces-(Aspect-Link-Getters).md
    - Copy Functionality: Copy-Functionality.md
    - Binary Exporting: Binary-Exporting.md
    - Equality Checks: Equality-Checks.md
    - Translation Masks: Translation-Masks.md
    - Flags and Enums: Flags-and-Enums.md
    - Asset Links: AssetLink.md
    - Binary Format Complexity Abstraction: Binary-Format-Complexity-Abstraction.md
    - Create, Duplicate, and Override: Create,-Duplicate,-and-Override.md
    - Abstract Subclassing: Abstract-Subclassing.md
    - Printing: Printing.md
    - Typical Mod Construction and Importing: Typical-Mod-Construction-and-Importing.md

index: Pages/index.md