name: Dev

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        sln:
          - Mutagen.Records.sln
          - Mutagen.Records.Linux.sln
        exclude:
          - os: ubuntu-latest
            project: Mutagen.Records.sln
          - os: macos-latest
            project: Mutagen.Records.sln
          - os: windows-latest
            project: Mutagen.Records.Linux.sln

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.*
    - name: Install dependencies
      run: |
        dotnet clean Mutagen.Records.sln -c Release && dotnet nuget locals all --clear
        dotnet restore ${{ matrix.sln }}
    - name: Build
      run: dotnet build ${{ matrix.sln }} -c Release --no-restore
    - name: Test
      run: dotnet test ${{ matrix.sln }} -c Release --no-build
