name: Release

on:
  push:
    branches: [ release ]
  pull_request:
    branches: [ release ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.*
    - name: Install dependencies
      run: |
        dotnet clean Mutagen.Records.sln -c Release && dotnet nuget locals all --clear
        dotnet restore Mutagen.Records.sln
    - name: Build
      run: dotnet build Mutagen.Records.sln -c Release --no-restore
    - name: Test
      run: dotnet test Mutagen.Records.sln -c Release --no-build
