name: Publish

on:
  release:
    types: [published]
    
jobs:
  release:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.*
    - name: Install dependencies
      run: |
        dotnet clean Mutagen.Records.sln -c Release && dotnet nuget locals all --clear
        dotnet restore Mutagen.Records.sln
    - name: Build
      run: dotnet build Mutagen.Records.sln --no-restore -c Release /p:Version=${{ github.event.release.tag_name }} -p:PackageReleaseNotes="See https://github.com/Mutagen-Modding/Mutagen/releases/tag/${{ github.event.release.tag_name }}"
    - name: Test
      run: dotnet test Mutagen.Records.sln --no-build -c Release
    - name: Publish to Github
      uses: svenstaro/upload-release-action@v2
      with:
        file: "**/*.nupkg"
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.event.release.tag_name }}
        file_glob: "true"
    - name: Publish to Nuget.org
      run: dotnet nuget push **/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --no-symbols true

#  notification:
#    runs-on: ubuntu-latest
#    needs: release
#    steps:
#    - name: Discord notification
#      env:
#        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
#      uses: Ilshidur/action-discord@0.3.0
#      with:
#        args: '**Mutagen v{{ EVENT_PAYLOAD.release.tag_name }}**\n{{ EVENT_PAYLOAD.release.body }}'
