name: Wiki

on:
  push:
    branches: [ dev ]

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      # Additional steps to generate documentation in "Documentation" directory
      - name: github-docs-to-wiki
        uses: cmbrose/github-docs-to-wiki@v0.24
        with:
          githubToken: ${{ secrets.ACCESS_TOKEN }}
          defaultBranch: "docs/"